apiVersion : v1

kind : Service

metadata : 
  namespace : deep-fake-ns 
  name : deepfake-service

spec :
  type : NodePort

  selector :
   app : deepfake

  ports:
    - port : 80
      nodePort : 30008
      targetPort : 8080

