FROM python:3.12.9-slim

WORKDIR /app

COPY /requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY /fast_api_inference ./fast_api_inference

CMD ["fastapi", "run","fast_api_inference/inference.py","--port","8080"]
