apiVersion : v1

kind : Service

metadata : 
  namespace : deep-fake-ns 
  name : deepfake-service

spec :
  type : LoadBalancer

  selector :
   app : deepfake

  ports:
    - port : 80
      targetPort : 8080

